import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { MessageCircle, Send, X } from "lucide-react";
import { VetReport } from "@shared/schema";
import { generateVetReportPDF } from "@/lib/pdf-generator";
import { generateSimplifiedReportPDF } from "@/lib/simplified-pdf-generator";

interface WhatsAppShareProps {
  report: VetReport;
  trigger?: React.ReactNode;
}

export function WhatsAppShare({ report, trigger }: WhatsAppShareProps) {
  const [isOpen, setIsOpen] = useState(false);
  const [phoneNumber, setPhoneNumber] = useState("");
  const [isGenerating, setIsGenerating] = useState(false);

  const handleSendToWhatsApp = async () => {
    if (!phoneNumber.trim()) {
      alert("Please enter a valid phone number");
      return;
    }

    setIsGenerating(true);
    
    try {
      // Generate PDF
      const pdf = report.reportType === 'biochemistry' 
        ? generateVetReportPDF(report)
        : generateSimplifiedReportPDF(report);
      
      // Create filename
      const labTestName = report.reportType?.replace(/_/g, ' ').replace(/\b\w/g, l => l.toUpperCase()) || 'Laboratory Report';
      const parentName = report.parentsName || 'Unknown';
      const patientName = report.patientName || 'Unknown';
      const currentDate = new Date().toISOString().split('T')[0];
      const filename = `${labTestName}_${parentName}_${patientName}_${currentDate}.pdf`;

      // Convert PDF to blob
      const pdfBlob = pdf.output('blob');
      
      // Create a temporary download link to get the PDF file
      const pdfDataUrl = await new Promise<string>((resolve) => {
        const reader = new FileReader();
        reader.onload = () => resolve(reader.result as string);
        reader.readAsDataURL(pdfBlob);
      });

      // Create WhatsApp message
      const message = `Hello! Please find attached the veterinary laboratory report for ${patientName}.\n\n` +
                     `Report Details:\n` +
                     `• Patient: ${patientName}\n` +
                     `• Test Type: ${labTestName}\n` +
                     `• Report Date: ${currentDate}\n` +
                     `• Generated by: ThePetNest Laboratory\n\n` +
                     `For any queries, please contact us at:\n` +
                     `📞 8848216190 | 8590433937\n` +
                     `📧 support.trivandrum@thepetnest.com`;

      // Format phone number (remove spaces, add country code if needed)
      let formattedNumber = phoneNumber.replace(/\s+/g, '');
      if (!formattedNumber.startsWith('+')) {
        // Assume Indian number if no country code
        if (formattedNumber.startsWith('0')) {
          formattedNumber = '+91' + formattedNumber.substring(1);
        } else if (formattedNumber.length === 10) {
          formattedNumber = '+91' + formattedNumber;
        }
      }

      // Create WhatsApp URL with message
      const whatsappUrl = `https://wa.me/${formattedNumber.replace('+', '')}?text=${encodeURIComponent(message)}`;
      
      // Download the PDF first so user can manually attach it
      const downloadLink = document.createElement('a');
      downloadLink.href = pdfDataUrl;
      downloadLink.download = filename;
      document.body.appendChild(downloadLink);
      downloadLink.click();
      document.body.removeChild(downloadLink);

      // Small delay to ensure download starts
      setTimeout(() => {
        // Open WhatsApp
        window.open(whatsappUrl, '_blank');
        setIsOpen(false);
        setPhoneNumber("");
      }, 1000);

    } catch (error) {
      console.error("Error sending to WhatsApp:", error);
      alert("Error preparing report for WhatsApp. Please try again.");
    } finally {
      setIsGenerating(false);
    }
  };

  const defaultTrigger = (
    <Button variant="outline" className="gap-2">
      <MessageCircle className="h-4 w-4 text-green-600" />
      Send to WhatsApp
    </Button>
  );

  return (
    <Dialog open={isOpen} onOpenChange={setIsOpen}>
      <DialogTrigger asChild>
        {trigger || defaultTrigger}
      </DialogTrigger>
      <DialogContent className="sm:max-w-md">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <MessageCircle className="h-5 w-5 text-green-600" />
            Send Report via WhatsApp
          </DialogTitle>
        </DialogHeader>
        <div className="space-y-4">
          <div className="space-y-2">
            <Label htmlFor="phone">Customer Phone Number</Label>
            <Input
              id="phone"
              type="tel"
              placeholder="Enter phone number (e.g., +91 9876543210)"
              value={phoneNumber}
              onChange={(e) => setPhoneNumber(e.target.value)}
              className="text-base"
            />
            <p className="text-xs text-gray-500">
              Include country code for international numbers
            </p>
          </div>
          
          <div className="bg-green-50 dark:bg-green-900/20 p-3 rounded-lg">
            <p className="text-sm text-green-800 dark:text-green-200">
              📋 The report will be downloaded automatically, then WhatsApp will open with a pre-written message. 
              You can manually attach the downloaded PDF file in WhatsApp.
            </p>
          </div>

          <div className="flex gap-2 justify-end">
            <Button 
              variant="outline" 
              onClick={() => setIsOpen(false)}
              disabled={isGenerating}
            >
              <X className="h-4 w-4 mr-1" />
              Cancel
            </Button>
            <Button 
              onClick={handleSendToWhatsApp}
              disabled={isGenerating || !phoneNumber.trim()}
              className="bg-green-600 hover:bg-green-700 text-white"
            >
              {isGenerating ? (
                <>
                  <div className="h-4 w-4 mr-2 animate-spin border-2 border-white border-t-transparent rounded-full" />
                  Preparing...
                </>
              ) : (
                <>
                  <Send className="h-4 w-4 mr-1" />
                  Send to WhatsApp
                </>
              )}
            </Button>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  );
}